project: "default"

environmentConfig:
  resourcePrefix: ""
  accountId: ""
  partition: ""
  clusterName: ""
  clusterFqdn: ""
  region: ""
  bootstrap:
    awsVpcId: ""
    awsExternalDnsRoleArn: ""
    awsEbsCsiDriverRoleArn: ""
    awsLbcRoleArn: ""