apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Base platform for HSP on AWS
  - ../hsp-aws-platform
  # CloudNativePG operator HelmApplication on top of the base
  - cloudnative-pg-operator-app.yaml
