apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-cd
  - cilium
  - crds
  - aws
  - crossplane
  - crossplane-compositions
  - karpenter
  - kyverno
  - kube-prometheus-stack
  - cert-manager